language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - jolorenzom@gmail.com
script:
#Test unitario y de integracion en develop
- mvn verify
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
- mvn sonar:sonar -Dsonar.projectKey=jolomoreno_IWVG.SwC.JoseLorenzo -Dsonar.organization=jolomoreno-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR
